app:
  title: Flagsmith Plugin Dev
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007

# Mock proxy endpoint - requests are intercepted by MSW
proxy:
  endpoints:
    '/flagsmith':
      target: 'http://localhost:7007'
